# Site/SEO settings
email: contactme@chingchinglee.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Ching Ching
title: Cook it!
description: >
  I love food. And I love sharing my recipes to you.
url: http://barber.samesies.io
twitter_username: chingchinglcc
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/chingchinglcc
  - name: instagram
    url: https://www.instagram.com/the_diary_of_allison
  - name: linkedin
    url: https://www.linkedin.com/in/ching-ching-lee-235551a5/
  - name: github
    url: https://github.com/chingchinglcc/
  - name: codepen
    url: https://codepen.io/allisonching/
# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Thomas Vaeth
    bio: Thomas Vaeth was born in New York, raised in Pennsylvania, and transplanted in Washington. He was a Web Developer at Urban Influence, but now he's a Software Engineer at Getty Images.
    url: http://thomasvaeth.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
