# Site/SEO settings
email: contactme@chingchinglee.com
baseurl: ""
paginate: 12
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/

name: Ching Ching
title: Code And Cook
description: 
  I love food. And I love sharing my recipes to you.
url: https://chingchinglcc.github.io/recipebook-jekyll
twitter_username: chingchinglcc
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/chingchinglcc
  - name: instagram
    url: https://www.instagram.com/the_diary_of_allison
  - name: linkedin
    url: https://www.linkedin.com/in/ching-ching-lee-235551a5/
  - name: github
    url: https://github.com/chingchinglcc/
  - name: codepen
    url: https://codepen.io/allisonching/

# Server
source: src
destination: _site

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Ching Ching Le
    bio:  I was born in Hong Kong, my mum is Thai and my dad is Hong Kong. I spent my childhood in Chiang Mai Thailand, then moved back to Hong Kong. And I am in Calgary, Canada now.
          I am geek developer who loves CSS, and always wanna be a CSS Ninja. If I am not coding and watching animation, then I am cooking.
    url: http://chingchinglee.com

# Build settings
markdown: kramdown
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md

sass:
  add_charset: true

# Navigation
docs:
- title: Recipes
  url: 

- title: Reviews
  url: /foodreview

- title: About
  url: /aboutme

# Collections
collections:
  reviews:
    output: true
    permalink: /reviews/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: foodreview
    values:
      layout: review